- server.js
I had originally intended this PR to be about adding an explicit route to `server.js` for the one (so far) dynamic page in the application (index.js) as exemplified in [the Next.js documentation](https://nextjs.org/docs/advanced-features/custom-server). However, after conducting a few experiments with this app and with Christian's demo app, I believe we don't need these explicit routes. The catch-all handler works fine for dynamic pages. The only difference between the explicit route config and the catch-all config is that the former [runs a couple of checks before handing over to the catch-all](https://stackoverflow.com/questions/59971672/custom-next-js-difference-between-getrequesthandler-and-render-functions) - and those checks are not relevant to us. 
I have not made any changes to …
> CFIN-290: Tidy up Express server configuration

- src/components/PageHead.js
- src/pages/index.js
- src/tests/pages/index.test.js
This PR goes through the [pattern library layout guide](https://www.york.ac.uk/pattern-library/layout/index.html) and applies some standard tags, page title, favicon etc.
I've also updated the page to use the full [basic grid](https://www.york.ac.uk/pattern-library/layout/grid.html) which gives us the standard responsive layout, which we can then update as we add new components to the page.
> CFIN-292 Apply the pattern library default layout to the index page

- .xo-config.json
- package-lock.json
- package.json
Following a comment this branch does not have eslint installed as part of the eslint-plugin-jsx-a11y install.
> CFIN 275 accessibility plugin without eslint plugin

- next.config.js
This is a small change to make Next account for the Stage in the AWS API Gateway URL when retrieving assets. I followed [these instructions in the Next documentation](https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix).
We might be able to remove this once we configure a stable domain name.
> CFIN-276 Retrieve assets from the correct URLs when running in API Gateway

- package.json
Also adds a command `formatandcheck` that replaces the previous behaviour of `check`.
> CFIN-299: Amend 'check' command to check formatting rather than fixing it

- package-lock.json
- package.json
- src/pages/index.js
This is a small change to use the latest version of the React pattern library which fixes the padding of the title bar (see [the PR](https://github.com/university-of-york/esg-lib-pattern-library-react-components/pull/18) for details).
I've also refactored to use some of the library components rather than our own `div`s where possible, and reintroduced the `prop-types` library which mysteriously vanished.
I would have liked to refactor the `SearchFailedMessage` to use an `Alert` component from the React pattern library, but it looks like they only exist for `Error` and `Success` at the moment, and not `Warning` which is what we use - a good candidate for someone to do in some downtime :smiley:
> CFIN-123 use the latest React pattern library, and refactor to use components

- .github/workflows/checks.yml
- package.json
Two tiny and loosely-related changes, one to update the GitHub workflow's name to be the same as the Courses API workflow, and the other to add a shorthand command that I will find really useful 😃
> Update GitHub workflow name for npm checks and add shorthand command

- package.json
- src/components/Search.js
- src/pages/index.js
- src/tests/components/Search.test.js
- src/tests/pages/index.test.js
This change adds a search box and basic search functionality to Course Search. You can try it out in my AWS sandbox account at https://y3cdpz4cgk.execute-api.eu-west-1.amazonaws.com/v1.
If a search term hasn't been entered it uses a default one for now - there's a separate story [CFIN-253](https://jira.york.ac.uk/browse/CFIN-253) about seeing a sensible list of courses when not entering a search term.
The following will be covered in separate PRs:
- Adding a sensible message when no search results are returned.
- Accessibility checks
---
> CFIN-303 allow users to enter a search term

- .github/workflows/deploy.yml
- next.config.js
- serverless.yml
Spoke to Chris earlier and for now we're going to use courses.app.york.ac.uk. This is to prevent people finding the prototype and getting confused by its lack of functionality before first release.
> CFIN-312 Update workflow and severless to use custom domain/URL

- src/components/Search.js
- src/pages/_document.js
This change covers two accessibility issues flagged by WAVE, if anyone has strong opinions about this I'd welcome any discussion!
- **ERROR: Set a page language** - this is fairly self-explanatory, and is done in a special `pages/_document.js` file which Next understands. I've copied the default page template as shown in [the example in the documentation](https://nextjs.org/docs/advanced-features/custom-document) and just added the `lang` attribute (this specific example is given as a reason to use `_document.js`).
- **ALERT: Fieldset without a legend** - WAVE flagged up that every form fieldset should have a legend; or, if a legend is deemed unnecessary, you probably don't need a fieldset. I read through some of the [accessibility guidelines around creating understandable pages through …
> CFIN-305 Improve course search page accessibility

- .xo-config.json
- package.json
- src/components/Tag.js
- src/components/TagList.js
- src/tests/components/Tag.test.js
- src/tests/components/TagList.test.js
This PR adds components `<TagList>` and `<Tag>`. The tag includes an `icon` parameter which aligns with the latest designs. These components could be used like 
```
<TagList>
<Tag icon="clock" mainText="Start September 2021" />
<Tag icon="graduation-cap" mainText="Undergraduate />
</TagList>
```
although I imagine that we'll want to [specialise](https://reactjs.org/docs/composition-vs-inheritance.html#specialization) the `<Tag>` component and create `<AwardTag>` and `<StartDateTag>` so that ultimately we use tags more like
```
<TagList>
<StartDateTag year="2021" />
<AwardTag award="BSc" />
</TagList>
```
and `<AwardTag>`, for example, will make use of the generic `<Tag>`:
```
const AwardTag ({ award }) => <Tag icon="institution" mainText={award} />
```
The `<Tag>` component will probably …
> CFIN-307: Create re-usable tag component

- README.md
It came up in discussion that we want all our documentation and guides to be easily found from the 'landing page' for our repo
> Add link to wiki to README

- .github/workflows/deploy.yml
- package-lock.json
- package.json
- serverless.yml
This turned out to be fairly straightforward once I realised that the environment variables need to be set in AWS Lambda (by Serverless) and found an [appropriate Serverless plugin](https://www.serverless.com/plugins/serverless-dotenv-plugin) to do the loading of the environment files.
Next.js only really understands 2 environments - development and production. In development mode (which you get by running `next dev` locally) it does babel transpiling, hot reloading, webpack on the fly etc, things that we don't really want it to do in AWS Lambda. So when we deploy the Next.js application to AWS Lambda, it really needs to be in production mode. But as a result, Next will only read environment variables from `.env.production`, and can't be told to look elsewhere for environment variables. …
> CFIN-357: Make "dev" Course Search use "dev" Courses API

- README.md
Following a comment by Nicola about the location of the mobile testing text, this is now moved as a sub-heading inside the testing section.
> CFIN-348 Changed location of mobile testing information

- src/components/Search.js
- src/pages/index.js
- src/tests/components/Search.test.js
- src/tests/pages/index.test.js
This is a change to limit the number of results on the screen and inform the user how many results are returned. 
In the case that we are showing all results we will display the text "Showing all 5 results for Archaeology".
In the case that there are more matches than we are showing we display the text "Showing the top 20 results for English"
You can see this functionality in my personal sandbox at: https://d28f89qbw6jana.cloudfront.net/?search=english
> CFIN 361 number of search results

- .env.development
- .env.production
- .env.test
- src/components/Search.js
- src/pages/index.js
- src/tests/components/Search.test.js
- src/tests/pages/index.test.js
A few tests have been updated to allow us to test different parts of the Courses API url being called. 
There is an option to put COURSES_API_MAX_RESULTS in a single .env file as it's a global value, however we have used the separate files for this PR, has anyone any preferences either way?
> CFIN-374 Show a maximum of 20 course search results

- package-lock.json
- package.json
This fixes the most recent Dependabot security update. I've tested it in an AWS sandbox environment.
> Bump Next.js version

- src/pages/index.js
- src/tests/pages/index.test.js
This is a small change based on @FergusMcGlynn 's suggestion to remove the `numberOfResultsShown` property from `index.js`
> CFIN-244 refactor index.js to remove numberOfResultsShown property

- src/components/Search.js
This means that the application will work when accessed through AWS API gateway.
This is an issue that cropped up when testing CFIN-244, where we saw the search form didn't work when deployed to an AWS sandbox account due to the `/v1/` in the path of the API gateway URL - in this case it's a tiny fix to make the form work.
> Submit Course Search form requests to the index page rather than the top level of the domain

- serverless.yml
Next.js v10 adds "[sharp](https://github.com/lovell/sharp)" (an image processing module) as a dependency. It is > 50 MB in size uncompressed, and was bloating our deployment bundle from ~15 MB to ~38 MB (compressed). The deployment bundle size negatively affects the Lambda's (and therefore Course Search's) performance. Sharp isn't needed at runtime (I'm fairly sure) so it can be excluded from the deployment bundle. I have deployed this version to my sandbox and verified that the app behaves as it should.
> Exclude "sharp" dependency from deployment bundle

- src/components/CourseSearchResults.js
- src/components/Search.js
- src/pages/index.js
- src/tests/components/CourseSearchResults.test.js
- src/tests/components/Search.test.js
- src/tests/pages/index.test.js
This PR includes changes to ensure that no search results, and no search description text (e.g. "showing top n results"), are presented when there are no search terms. A future PR will add functionality to display a message to the user stating that they didn't enter any search terms.
[Try it out in my sandbox](https://courses.ferg.dev.app.york.ac.uk/)
> CFIN-384: Show no search results when no search terms entered

- .github/workflows/application-size.yml
- .github/workflows/report-package-size.yml
- package.json
This PR is a suggestion, so thoughts would be very welcome! :thought_balloon: 
Inspired by #65 where I upgraded the application to Next 10 which unwittingly increased the package size, and #69 from Ferg which excluded the relevant dependency to shrink it back down, I thought it might be a good idea to get more visibility of our package size. This PR adds a workflow that uses the [compressed-size-action](https://github.com/marketplace/actions/compressed-size-action) (from the maintainers of preactjs) to do exactly that.
I recreated the above PRs in a demo repo to see what it'd look like, you can check them out [here](https://github.com/university-of-york/ce666-demo-repo/pull/6) and [here](https://github.com/university-of-york/ce666-demo-repo/pull/7) (and …
> Add workflow to check the package size

- src/components/CourseSearchResults.js
- src/pages/index.js
- src/tests/components/CourseSearchResults.test.js
- src/tests/pages/index.test.js
- src/tests/utils/searchTerms.test.js
- src/utils/searchTerms.js
This solution relies on discriminating between `searchTerm === undefined` (meaning no search has been conducted yet) and `searchTerm === ""` (meaning an empty search has been conducted). I thought that was a bit of a subtle distinction so I've introduced a couple of helper functions to make these scenarios explicit.
[Try it out in my sandbox](https://courses.ferg.dev.app.york.ac.uk/)
> CFIN-383: Show "no results" message to user when they enter no search terms

- src/components/Search.js
- src/tests/components/Search.test.js
- src/tests/pages/index.test.js
When there are no search results, up til now, we have been presenting a message stating "Showing 0 results for <search term>" and also showing a message saying "Sorry, there were no results for this search". This PR removes the first message in this situation.
> CFIN-393: Omit "showing 0 results" when no search results

- src/components/PageHead.js
[Lighthouse](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fcourses.dev.app.york.ac.uk%2F) reports three issues of unused JS:
- The pattern library's `app.min.js`
- A Google APIs script (loaded via `app.min.js`)
- A Next.js static chunk
I think that the Next.js static chunk should be treated as a consequence of us choosing to use the framework, so it's not something we should be looking to customise unless we really need the benefits.
Therefore this PR focuses on removing `app.min.js`, which in itself is a fairly simple change but has some implications.
It's been mentioned in the past that two parts of core pattern library functionality are delivered through JS:
- The sticky footer
- The "Show More" nav bar functionality
I also tried to consider any other global …
> CFIN-407 remove pattern library javascript

- src/pages/index.js
- src/tests/pages/index.test.js
- src/tests/utils/searchForCourses.test.js
- src/utils/searchForCourses.js
This is the second of 2 alternative options for a refactor.
This one extracts the block of code that handles calling the Courses API out of getServerSideProps and into its own module, with its own tests, most of which have been moved over from `index.test.js`. This one makes `index.js` more concise - although it adds more code in total, because of the extra tests.
Do you prefer one or the other? Or neither?
> CFIN-412: Refactor option 2 - move Courses API search to new module

- serverless.yml
One of the opportunities for optimising performance suggested by Lighthouse is to enable text compression. There is a trade off between the transmission speed gains from smaller files vs the overhead of doing the compression, which is why this change only compresses responses above a certain size (1000 bytes), aligning with what AWS CloudFront does (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html).
Lightspeed average score before change: 51
Lightspeed average score after change: 62
Lightspeed average score compress all responses:  60
> CFIN-409: Compress API responses > 1Kb

- serverless.yml
This is the result of an investigation to see if we can improve the response time of the Course Search application (purely focused on the front-end - other investigations into the Courses API and Funnelback are happening separately). I looked at package size and memory/CPU allocation. 
In short, **there's no noticeable effect on the average performance score when altering package size or memory/CPU allocation**, but I think the changes are worth doing for other reasons (deployment time and cost) so I'm raising this PR.
- I identified a number of files that are currently packaged up that aren't necessary in the lambda, and added exclude rules for them.
- I identified a few more of the larger `node_modules` runtime dependencies (>=~1MB) that we don't appear to be using, and added exclude …
> CFIN-417 Improve Course Search response time

- .github/workflows/percy-visual-testing.yml
- src/tests/visual/percyVisualTesting.js
Two things I noticed when testing Percy:
- We don't take snapshots when pushing to our default branch - future branches won't compare changes against the correct base snapshot unless we do this.
- For whatever reason the Percy script still runs forever on my local machine unless `process.exit()` is present - I saw no harm in adding it so that it will hopefully work for everyone.
> Run visual testing on push to dev

- package-lock.json
- package.json
See https://github.com/serverless/serverless/issues/8712
"percy-agent", which also used the insecure version of Axios [has been updated](https://github.com/percy/percy-agent/issues/600), but that doesn't require a code change in this project because "@percy/script" (used by this project) pulls in the latest version of "percy-agent"
> Update Serverless to fix security vulnerability in Axios

- package-lock.json
This change is purely the result of running "npm audit fix". It resolves the dependabot warning about Axios that's currently appearing on Github, as well as some other issues.
> Fix npm dependency vulnerabilities

- src/tests/performance/lighthouseTesting.js
I've noticed that the lighthouse performance checks for mobile are consistently scoring above 90 when running in a GitHub workflow and locally ([94 in this PR](https://github.com/university-of-york/uoy-app-course-search/runs/1987262692?check_suite_focus=true)).
I think we should be aiming to maintain this high mobile performance. It also feels nice to have a consistent performance target for mobile and desktop.
> Update lighthouse performance check to align mobile/desktop targets to 90

- package-lock.json
I have checked out the branch and run it successfully locally.
Bumps [ssri](https://github.com/npm/ssri) from 6.0.1 to 6.0.2.
- [Release notes](https://github.com/npm/ssri/releases)
- [Changelog](https://github.com/npm/ssri/blob/v6.0.2/CHANGELOG.md)
- [Commits](https://github.com/npm/ssri/compare/v6.0.1...v6.0.2)
Signed-off-by: dependabot[bot] <support@github.com>
> Bump ssri from 6.0.1 to 6.0.2

- public/stylesheets/styles.css
The reflow options previously caused tags to reflow to be half-width at mobile viewports. This reduces the width at which that applies. This also adds a 100% width on reflow if a screen somehow gets the tag width to be less than 120px.
> CFIN-456 Fix reflowing on mobile

- package-lock.json
- src/components/Course.js
- src/tests/components/Course.test.js
The course links until this change have appeared in the accessibility tree with link text containing the course's title and all of its tags eg. 'Music - BA (Hons) Undergraduate BA (Hons) Start 2021 3 years full-time'
This change makes it 'Music - BA (Hons)'.
With grateful acknowledgement of Fergus's detailed notes on the JIRA story of how to tackle this.
> CFIN-450 Make the accessibility tree course links be the course title and award

- src/components/CourseDetails.js
- src/tests/components/CourseDetails.test.js
This came up at the stakeholder meeting - Paul Armstrong requested this change, and I tend to agree that a calendar is more appropriate for a date than a clock. 
Here's how it looks:
What do we think?
> Use calendar icon for course start rather than clock

- src/pages/index.js
- src/tests/pages/index.test.js
This is to allow Course Search to accept the same query parameter as Course Finder, so that it can be used as a variant in a Google Optimize redirect test.
> CFIN-509: Allow 'q' query param as synonym for 'search'

- .github/workflows/build.yml
- .github/workflows/code-formatting.yml
- .github/workflows/deployment.yml
- .github/workflows/linting.yml
- .github/workflows/package-size.yml
- .github/workflows/performance-checks.yml
- .github/workflows/publish-architecture.yml
- .github/workflows/tests.yml
- .github/workflows/visual-tests.yml
- README.md
Our README is very detailed, but I've felt overwhelmed by it for a while - times have moved on and we have more knowledge of AWS and npm, and the focus should be on being a getting started guide rather than a go-to for every single detail.
This PR is a (perhaps bold) suggestion to trim down the README to some of the essentials, with some information being moved to the GitHub wiki, and some being removed altogether.
At the same time I decided to tackle the GitHub workflows, opting to split out the checks into separate workflows - this gives us more visibility of exactly what goes wrong in a build, at the trade-off of spending more GitHub build minutes. I think it's worth the cost.
Splitting out the checks also makes it very easy to have a clean set of GitHub status badges that immediately …
> Condense the README and add GitHub status badges

- docs/architecture/c4-model.dsl
This PR updates the system architecture diagrams to better reflect the fact that course pages are on www.york.ac.uk, and includes a new container diagram which shows that the data sources are both the course pages and the external courses feed.
> Update c4 model

- package-lock.json
- package.json
- public/js/analytics.js
- src/components/PageHead.js
- src/pages/_app.js
- src/tests/performance/lighthouseTesting.js
This PR installs Google Tag Manager into Course Search. [Google's instructions for installing GTM](https://developers.google.com/tag-manager/quickstart) don't work very well for React/Next apps, which has led to development of [an npm library](https://www.npmjs.com/package/react-gtm-module) specifically for installing GTM in a React/Next app. I followed [these instructions](https://www.learnbestcoding.com/post/9/easiest-way-to-integrate-google-analytics-with-react-js-and-next-js) and it seems to work well - I have verified with Digital Marketing that it works as expected.
There are two reasons why we almost certainly need to install GTM into Course Search:
1. We want to track various metrics to help us determine whether Course Search provides a better user experience than Course Finder. …
> CFIN-522: Install Google Tag Manager

- README.md
- cypress.json
* Prevent Cypress from generating video/plugin/support files
* It generates these files every time tests are run - they're not currently of any use
* Update README with info on how to run the app's Cypress tests
> Minor tweaks to Cypress setup

- README.md
When deploying Course Search to a sandbox account, it's not obvious what URL it can be accessed from, nor why the styling doesn't look right. This pull requests adds some text to the README to clarify these issues.
> Add instructions on accessing app after sandbox deployment

- src/utils/logger.js
The fields `pid` and `hostname` are included by default in Pino, they aren't very useful to us since this application is serverless. This merge would remove the two fields from the logger output object.
> CFIN-583: Remove Pino default fields

- src/pages/index.js
Noticed that I have forgotten to log when the user loads the courses index page and when they conduct an empty search. This functionality was previously available but I had moved the existing logger elsewhere. This PR hopefully fixes this oversight.
> CFIN-583: Add missing loggers
